### ISSUE TITLE
Constant time newtype wrapper?

### ISSUE THREAD

**Issue by burdges** [valarauca/consistenttime#1]
Is it wise to do constant time operations via a wrapper newtype `struct CT<T>(pub T)` similar to the `std::num::Wrapping`?  I kinda think it'd make auditing the resulting code easier myself.

**Comment by burdges** [comment]
I suppose it's actually less clear for the functions provided here.  I'll close for now.

**Comment by valarauca** [comment]
For auditing I can spin off a second branch and dump the macro expand source + the x86 and x64 asm dumps if you think that would help?

Also for long term testing should I add `#[no_mangle]` and `extern "c"` to the Function declarations? That should allow the output object file to be linked to a C program for more fine grain testing.
